name: ${project.name}
main: ${project.groupId}.chatbot.MintChatBot
version: ${project.version}
author: ucchy
description: ${project.description}
softdepend: [Vault, LunaChat, SuperVanish]

commands:
  chatbot:
    description: chatbotのコマンド
    aliases: [cb, bot]
    usage: |
           /<command> ask (message) - プライベートチャットでBotに応答を尋ねます。
           /<command> reload - 設定をリロードします。
    permission: chatbot.command
    permission-message: 'パーミッション "<permission>" が無いため実行できません。'
  ircbot:
    description: ircbotのコマンド
    aliases: [ib, irc]
    usage: |
           /<command> connect - チャンネルに接続します。
           /<command> disconnect - チャンネルから切断します。
           /<command> reconnect - チャンネルに再接続します。
           /<command> message (message) - チャンネルに発言します。
           /<command> op (target) - 指定したニックネームのユーザーに、チャンネル管理者を与えます。IRCBotがチャンネル管理者である必要があります。
           /<command> kick (target) [reason] - 指定したニックネームのユーザーを、チャンネルからキックします。IRCBotがチャンネル管理者である必要があります。
    permission: chatbot.irc.command
    permission-message: 'パーミッション "<permission>" が無いため実行できません。'

permissions:
  chatbot.command:
    description: 'chatbot コマンドの使用権限'
    default: true
  chatbot.command.reload:
    description: 'chatbot reload コマンドの使用権限'
    default: op
  chatbot.command.ask:
    description: 'chatbot ask コマンドの使用権限'
    default: true
  chatbot.irc.command:
    description: 'ircbot コマンドの使用権限'
    default: op
  chatbot.irc.connect:
    description: 'irc connect コマンドの使用権限'
    default: op
  chatbot.irc.disconnect:
    description: 'irc disconnect コマンドの使用権限'
    default: op
  chatbot.irc.reconnect:
    description: 'irc disconnect コマンドの使用権限'
    default: op
  chatbot.irc.message:
    description: 'irc message コマンドの使用権限'
    default: op
  chatbot.irc.op:
    description: 'irc op コマンドの使用権限'
    default: op
  chatbot.irc.kick:
    description: 'irc kick コマンドの使用権限'
    default: op
  chatbot.irc.*:
    description: 'ircbot コマンドの全ての権限'
    children:
      chatbot.irc.command: true
      chatbot.irc.connect: true
      chatbot.irc.disconnect: true
      chatbot.irc.reconnect: true
      chatbot.irc.message: true
      chatbot.irc.op: true
      chatbot.irc.kick: true
  chatbot.*:
    description: 'chatbot の全ての権限'
    children:
      chatbot.command: true
      chatbot.command.reload: true
      chatbot.command.ask: true
      chatbot.irc.*: true
